const data = {
  常微分: [
    {
      week: 1,
      node: 1,
      len: 2,
      name: "常微分",
      tname: "老师姓名",
      addr: "303",
    },
    {
      week: 3,
      node: 7,
      len: 2,
      name: "常微分",
      tname: "老师姓名",
      addr: "326",
    },
  ],
  物理: [
    {
      week: 1,
      node: 5,
      len: 2,
      name: "大学物理",
      tname: "老师姓名",
      addr: "426",
    },
    {
      week: 3,
      node: 5,
      len: 2,
      name: "大学物理",
      tname: "老师姓名",
      addr: "426",
    },
  ],
  数分: [
    {
      week: 1,
      node: 7,
      len: 2,
      name: "数分",
      tname: "老师姓名",
      addr: "507",
    },
    {
      week: 2,
      node: 1,
      len: 2,
      name: "数分",
      tname: "老师姓名",
      addr: "405",
    },
    {
      week: 4,
      node: 1,
      len: 2,
      name: "数分",
      tname: "老师姓名",
      addr: "515",
    },
  ],
  近现代史: [
    {
      week: 2,
      node: 5,
      len: 2,
      name: "近现代史",
      tname: "老师姓名",
      addr: "511",
    },
  ],
  乒乓球: [
    {
      week: 2,
      node: 7,
      len: 2,
      name: "乒乓球",
      tname: "老师姓名",
      addr: "南校乒羽馆",
    },
  ],
  教育学: [
    {
      week: 3,
      node: 9,
      len: 3,
      name: "教育学",
      tname: "老师姓名",
      addr: "307",
    },
  ],
  劳动教育: [
    {
      week: 4,
      node: 5,
      len: 4,
      name: "劳动教育",
      tname: "老师姓名",
      addr: "201",
    },
  ],
  英语: [
    {
      week: 5,
      node: 1,
      len: 2,
      name: "英语",
      tname: "老师姓名",
      addr: "218",
    },
  ],
  高考志愿: [
    {
      week: 5,
      node: 7,
      len: 2,
      name: "高考志愿",
      tname: "老师姓名",
      addr: "106",
    },
  ],
  形策: [
    {
      week: 6,
      node: 7,
      len: 2,
      name: "形策",
      tname: "老师姓名",
      addr: "211",
    },
  ],
};
const pointColor = [
  {backgroundColor:"#ffccc7",color:"#f5222d"},
  {backgroundColor:"#ffd8bf",color:"#fa541c"},
  {backgroundColor:"#ffe7ba",color:"#fa8c16"},
  {backgroundColor:"#f4ffb8",color:"#a0d911"},
  {backgroundColor:"#d9f7be",color:"#52c41a"},
  {backgroundColor:"#b5f5ec",color:"#13c2c2"},
  {backgroundColor:"#bae7ff",color:"#1890ff"},
  {backgroundColor:"#d6e4ff",color:"#2f54eb"},
  {backgroundColor:"#efdbff",color:"#722ed1"},
  {backgroundColor:"#ffd6e7",color:"#eb2f96"},
];
const timeTable = [
  { start: "07:30", end: "08:10" },
  { start: "08:20", end: "09:00" },
  { start: "09:10", end: "09:50" },
  { start: "10:00", end: "10:40" },
  { start: "10:50", end: "11:30" },
  { start: "14:20", end: "15:00" },
  { start: "15:10", end: "15:50" },
  { start: "16:00", end: "16:40" },
  { start: "16:50", end: "17:30" },
  { start: "18:30", end: "19:10" },
  { start: "19:20", end: "20:00" },
  { start: "20:10", end: "20:50" },
];
export { data, pointColor, timeTable };
