export const data = [
  {
    week: 1,
    node: 1,
    len: 2,
    name: "常微分",
    tname: "",
    addr: "303",
    mark: "",
  },
  {
    week: 1,
    node: 5,
    len: 2,
    name: "大学物理",
    tname: "",
    addr: "406",
    mark: "",
  },
  { week: 1, node: 7, len: 2, name: "数分", tname: "", addr: "507", mark: "" },
  { week: 2, node: 1, len: 2, name: "数分", tname: "", addr: "405", mark: "" },
  {
    week: 2,
    node: 5,
    len: 2,
    name: "近现代史",
    tname: "",
    addr: "511",
    mark: "",
  },
  {
    week: 2,
    node: 7,
    len: 2,
    name: "乒乓球",
    tname: "",
    addr: "南校乒羽馆",
    mark: "",
  },
  { week: 3, node: 5, len: 2, name: "物理", tname: "", addr: "426", mark: "" },
  {
    week: 3,
    node: 7,
    len: 2,
    name: "常微分",
    tname: "",
    addr: "326",
    mark: "",
  },
  {
    week: 3,
    node: 9,
    len: 2,
    name: "教育学",
    tname: "",
    addr: "307",
    mark: "",
  },
  { week: 4, node: 1, len: 2, name: "数分", tname: "", addr: "515", mark: "" },
  {
    week: 4,
    node: 5,
    len: 4,
    name: "劳动教育",
    tname: "",
    addr: "201",
    mark: "",
  },
  { week: 5, node: 1, len: 2, name: "英语", tname: "", addr: "218", mark: "" },
  {
    week: 5,
    node: 7,
    len: 2,
    name: "高考志愿",
    tname: "",
    addr: "106",
    mark: "",
  },
  { week: 6, node: 7, len: 2, name: "形策", tname: "", addr: "211", mark: "" },
];
